# Generated by Django 5.0.6 on 2024-06-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=55)),
                ('email_address', models.EmailField(max_length=100)),
                ('country', models.CharField(max_length=200)),
                ('membership_level', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('point_expiry_date', models.DateField()),
                ('member_expiry_date', models.DateField()),
                ('membership_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('product_sale_price', models.FloatField()),
                ('product_location', models.CharField(max_length=50)),
                ('product_width', models.IntegerField()),
                ('product_height', models.IntegerField()),
                ('product_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('salt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('hire_date', models.DateField()),
                ('contract_expiry_date', models.DateField()),
                ('employee_role', models.CharField(max_length=20)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.department')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.user')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_start', models.DateField()),
                ('leave_end', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.FloatField()),
                ('bonus', models.FloatField()),
                ('net_pay', models.FloatField()),
                ('date_of_month', models.DateTimeField()),
                ('benefit', models.CharField(max_length=50)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('invoice_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_quantity', models.IntegerField()),
                ('invoice_price_per_unit', models.FloatField()),
                ('payment_terms', models.CharField(max_length=30)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.invoice')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.products')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('points_earned', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.employee')),
                ('membership_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.membership')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionProduct',
            fields=[
                ('transaction_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_quantity', models.IntegerField()),
                ('transaction_price_per_unit', models.FloatField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.products')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.transaction')),
            ],
        ),
    ]
