# Generated by Django 4.2.13 on 2024-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
