# Generated by Django 4.2.13 on 2024-06-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
