# Generated by Django 5.0.7 on 2024-07-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
