# Generated by Django 4.2.13 on 2024-07-14 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_images/'),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(default='annual', max_length=10),
        ),
        migrations.AddField(
            model_name='leave',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_leave_balance', models.IntegerField(default=14)),
                ('medical_leave_balance', models.IntegerField(default=365)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.employee')),
            ],
        ),
    ]
