# Generated by Django 4.2.13 on 2024-07-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_date',
        ),
    ]
