# Generated by Django 4.2.13 on 2024-07-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0003_attendance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
    ]
