# Generated by Django 4.2.13 on 2024-07-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0003_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
