# Generated by Django 4.2.13 on 2024-07-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0005_remove_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
