# Generated by Django 4.2.13 on 2024-07-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0006_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
