# Generated by Django 4.2.13 on 2024-07-16 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0007_alter_leave_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproduct',
            name='payment_terms',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Card', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_terms',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Card', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
