# Generated by Django 4.2.13 on 2024-07-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0008_remove_invoiceproduct_payment_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc1106app.product')),
            ],
        ),
    ]
