# Generated by Django 4.2.13 on 2024-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0009_stockorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockorder',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
