# Generated by Django 4.2.13 on 2024-07-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0010_alter_stockorder_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockOrder',
        ),
    ]
