# Generated by Django 4.2.13 on 2024-07-17 07:06

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0011_delete_stockorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='benefit',
        ),
        migrations.AddField(
            model_name='payroll',
            name='cpf_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='hours_worked',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
