# Generated by Django 4.2.13 on 2024-07-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0013_usersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='created_at',
            new_name='expiry_date',
        ),
    ]
