# Generated by Django 5.0.7 on 2024-07-22 04:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc1106app', '0014_rename_created_at_usersession_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='uuid_filename',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uuid_filename',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
